server:
  port: 8761
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: thdtmdgk1!
#    key-store-type: PKCS12
#    keyAlias: client

spring:
  application:
    name: msa-discovery-service
  security:
    user:
      name: seungha
      password: thdtmdgk1!
    basic:
      enabled: true

eureka:
  client:
    register-with-eureka: false   # euraka? 나 자신은 제외
    fetch-registry: false         # registy? ?? ??? ???? ??? ??